version: '3'
services:
  app:
    container_name: app
    restart: always
    tty: true
    ports:
      - "3000:3000"
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

  redis:
    container_name: redis
    restart: always
    tty: true
    build:
      context: .
      dockerfile: ./docker/redis/dockerfile
    environment:
      SERVICE_NAME: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:lts
    platform: linux/arm64
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local
